version: "3.5"

services:
  mongo-test:
    tty: true
    stdin_open: true
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  cpid-solar-telemetry-test:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - mongo
    env_file: .env.test
